### ISSUE TITLE
docker client volume mapping problem

### ISSUE THREAD

**Issue by ogazioglu** [moosefs/moosefs-docker-cluster#13]
There is an issue with volume mapping of docker client. Just added this mapping below but it doesn't work.

    mfsclient:
     ...
      volumes:
        - /mnt/mfs:/mnt/moosefs

To test this
>$ docker-compose exec mfsclient bash
>$ echo "1" > /mnt/moosefs/test
>$ exit
>$ ls /mnt/mfs
>> _(empty - there is no test file)_

>$ cd /mnt/mfs
>$ cat .mooseart
>> _(no file)_

It seems that adding a file into the container's **/mnt/moosefs** folder works and the file is seen in the resources tab of the GUI. But it isn't reached from the docker volume map folder **/mnt/mfs**, which is still empty. In addition to this, adding another file to host directory has no effect and file isn't seen in the GUI.

In addition to this, if you add another docker client (mfsclient-2) to compose file which has another container name , volume-map and IP, and you get the test file in the second container's mount folder.

By the way, I have another machine that runs the cluster that was built with version 2 docker-compose.yml, but this issue does not exists there, host and container folders correctly mapped. So I compared the client folders, they are slightly different. version 2 has a .sh file but version 3 not.

**Comment by xandrus** [comment]
Hi,
It looks like correct docker behavior referencing to this documentation:
https://docs.docker.com/storage/volumes/
https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation

"Volumes use rprivate bind propagation, and bind propagation is not configurable for volumes."

So the host path is exported to docker and after mfsmount command execution, fuse mount stays only inside docker.

I will make a few tests and return with some observations.

By the way.
If you use Linux you can easily mount moosefs client on your host.
Just install moosefs client and  use master docker IP as a host:
```
mfsmount -H 172.20.0.2 /your/mfsmount/path
```

**Comment by ogazioglu** [comment]
I have same version docker and docker-compose in all linux servers in Hyper-V

OS : Ubuntu 18.04 bionic server
Docker version 19.03.11, build 42e35e61f3
docker-compose version 1.25.4, build 8d51620a

I know manually installing client outside of container is a solution. But this issue seems that a bug.

Because I had installed v3.0.103 container into my staging machine a few weeks ago from your repo with v2 docker-compose.yml file and it has worked as expected. So I mapped container's mount folder **/mnt/moosefs** to host's **/mnt/mfs** folder and I can read/write both of folders. It is still working by the way. Everything is ok there.

But a few day ago, while I was thinking to deploy my app which works with moosefs into production machine I pulled repo into the production another machine but the new v3.0.113 with v3 docker-compose.yml was downloaded. But there was a trouble. It seems that something changed on your side.

For ex. mfsmount command changed. In previous version there was start-client.sh file for bootstrapping client which takes -H arg. The command is below:

     mfsmount /mnt/moosefs -H mfsmaster

But in new version that changed to:

     mfsmount -f /mnt/moosefs

I guess that the mfsclient process locks the resource and docker is not able to synch files between folders. However, in same container I mapped another test folder to outside. For ex. **/test:/test** worked as expected. This issue occurs only in version 3.0.113 images and client container's **/mnt/moosefs** folder.

Furthermore, unfortunately I couldn't have downloaded previous healthy version because they had been deleted from docker hub.

**Comment by xandrus** [comment]
I will definitely take a closer look at that.

**Comment by xandrus** [comment]
Hi,

Can you try to change the permission type in volume definition to shared - like in this example:
```
mfsclient:
 ...
  volumes:
    - /mnt/mfs:/mnt/moosefs:shared
```
It should help in your case.

**Comment by ogazioglu** [comment]
Hi,

Yes, "shared" fixed this issue. Adding it to mfsclient's mapping is enough. Other containers that maps to that folder doesn't require "shared" flag.

Thank you.
